window.MANIFEST_MATRIX = [
  {
    "id": "41-19__tech-noir-v2",
    "verse_key": "41-19",
    "transition": "損 Sǔn (Decrease) -> 臨 Lín (Approach)",
    "verse_zh": "元吉无咎，安寧不殆。",
    "verse_en": "Supremely auspicious, without blame; peaceful and tranquil, free from peril.",
    "approach": "tech-noir-v2",
    "style": "datascape",
    "note": "Auspicious tone -> datascape depth corridors. Stylized graphic treatment, not photoreal.",
    "prompt": "Through a server-rack gateway, green wireframe grids recede into depth like data corridors. A lone figure at a curved console, hands at rest, phosphor scanlines washing across worn fingers. Cable bundles form a canopy above; cooling mist pours from vents, pooling like signal fog. One amber status LED blinks on a distant rack face. Phosphor-green tech-noir illustration, CRT scanlines, flat deep blacks, stylized graphic art, not photorealistic.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/41-19__tech-noir-v2.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d278a/4G0o-o9nAWk2RElJdCyKD_Zw9R1ifq.png",
    "generated_at": "2026-06-06T10:52:32"
  },
  {
    "id": "41-19__stipple",
    "verse_key": "41-19",
    "transition": "損 Sǔn (Decrease) -> 臨 Lín (Approach)",
    "verse_zh": "元吉无咎，安寧不殆。",
    "verse_en": "Supremely auspicious, without blame; peaceful and tranquil, free from peril.",
    "approach": "stipple",
    "style": "ink-landscape",
    "note": "Auspicious tone -> ink-landscape scene, stipple render. Same composition, matrix-skin finish.",
    "prompt": "Through a weathered stone gate, mossy steps descend like pale brushstrokes toward a still valley. In the midground a lone figure in a vermillion robe crosses a low bridge over calm water that mirrors the sky like spilled silver. Pine boughs frame the upper edge; terraced hills fade into amber dawn mist behind. Golden age science fiction stipple illustration, thousands of individual ink dots building luminous tonal gradients, figures emerging from darkness through pure pointillism technique, ethereal glowing quality, meticulous dot-work rendering every form, phosphor-green and amber palette on black.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/41-19__stipple.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d278b/K8uwOPl33C9r62LHEkLXb_vNlujvDD.png",
    "generated_at": "2026-06-06T10:52:35"
  },
  {
    "id": "58-25__tech-noir-v2",
    "verse_key": "58-25",
    "transition": "兌 Duì (Joyous Lake) -> 無妄 Wú Wàng (Innocence)",
    "verse_zh": "結網得解，受福安坐，終无患禍。",
    "verse_en": "The knotted net finds release; one receives blessing and sits at ease. In the end there is no trouble or calamity.",
    "approach": "tech-noir-v2",
    "style": "surveillance-feed",
    "note": "Blessing and ease -> voyeuristic surveillance framing. Graphic-novel treatment, stylized flats.",
    "prompt": "Through a rain-streaked window filmed by a dirty security camera, an old fisherman sits at ease on plastic crates by a concrete canal. A slack data cable curls at his feet like dark wire. A boat floats on black water reflecting sodium amber light; condensation softens the lens. Reed stalks sway as scan distortion. A green LED blinks on a junction box. Phosphor-green tech-noir illustration, CRT scanlines, flat deep blacks, stylized graphic art, not photorealistic.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/58-25__tech-noir-v2.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d278b/QFQassb-CmszHVaDyfGb3_kTnlhJ3a.png",
    "generated_at": "2026-06-06T10:52:40"
  },
  {
    "id": "58-25__stipple",
    "verse_key": "58-25",
    "transition": "兌 Duì (Joyous Lake) -> 無妄 Wú Wàng (Innocence)",
    "verse_zh": "結網得解，受福安坐，終无患禍。",
    "verse_en": "The knotted net finds release; one receives blessing and sits at ease. In the end there is no trouble or calamity.",
    "approach": "stipple",
    "style": "figures-in-mist",
    "note": "Blessing and ease -> fisherman at rest scene, stipple render. Matrix-skin finish on proven composition.",
    "prompt": "Beneath a thatched eave framing the view, an old fisherman sits at ease on worn planks, a loosened net slack at his feet like unraveled ink threads. In the midground a calm inlet catches dawn light; a small boat drifts, its lantern a single amber spark. Reed banks and pale hills recede into mist beyond. Golden age science fiction stipple illustration, thousands of individual ink dots building luminous tonal gradients, figures emerging from darkness through pure pointillism technique, ethereal glowing quality, meticulous dot-work rendering every form, phosphor-green and amber palette on black.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/58-25__stipple.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d278c/NQhM-IE_KXdKcFWn-YnNy_P7qcxOxl.png",
    "generated_at": "2026-06-06T10:52:44"
  },
  {
    "id": "28-23__tech-noir-v2",
    "verse_key": "28-23",
    "transition": "大過 Dà Guò (Great Exceeding) -> 剝 Bō (Splitting Apart)",
    "verse_zh": "廓落失業，跨禍度福，利無所得。",
    "verse_en": "Vast and vacant, livelihood lost; straddling disaster, crossing toward fortune. Profit is nowhere to be found.",
    "approach": "tech-noir-v2",
    "style": "terminal-dark",
    "note": "Loss and emptiness -> terminal-dark. Stylized phosphor shapes, graphic-novel contrast.",
    "prompt": "Inside a ruined server room doorway, an amber diagnostic light pulses through dust-choked darkness like a dying signal. Foreground: shattered tiles and a toppled empty chassis. Midground: a lone figure crosses a narrow catwalk over coolant pooling like dark data streams. Far off, rack silhouettes fade into static grain. One green cursor blinks on a cracked monitor. Phosphor-green tech-noir illustration, CRT scanlines, flat deep blacks, stylized graphic art, not photorealistic.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/28-23__tech-noir-v2.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d2790/BQZ-ViQtcYkVBTV-k73X0_dmPf3gDp.png",
    "generated_at": "2026-06-06T10:52:47"
  },
  {
    "id": "28-23__stipple",
    "verse_key": "28-23",
    "transition": "大過 Dà Guò (Great Exceeding) -> 剝 Bō (Splitting Apart)",
    "verse_zh": "廓落失業，跨禍度福，利無所得。",
    "verse_en": "Vast and vacant, livelihood lost; straddling disaster, crossing toward fortune. Profit is nowhere to be found.",
    "approach": "stipple",
    "style": "atmospheric-night",
    "note": "Loss and emptiness -> atmospheric-night scene, stipple render. Matrix-skin finish on the dark composition.",
    "prompt": "Inside a ruined gateway framing a vast empty courtyard, a single lantern gutters against the dark like a dying ember. Foreground: cracked flagstones and an overturned empty basket. Midground: a lone figure crosses a narrow plank between two pools of shadow. Far off, faint cold hills dissolve into black mist. One vermillion seal glows on a leaning post. Golden age science fiction stipple illustration, thousands of individual ink dots building luminous tonal gradients, figures emerging from darkness through pure pointillism technique, ethereal glowing quality, meticulous dot-work rendering every form, phosphor-green and amber palette on black.",
    "model": "fal-ai/z-image/turbo",
    "seed": 410419,
    "returned_seed": 410419,
    "image": "images/28-23__stipple.png",
    "source_url": "https://v3b.fal.media/files/b/0a9d2791/fHgr9SZzBN8ygrWYvJJtY_Z9fKNbpC.png",
    "generated_at": "2026-06-06T10:52:51"
  }
];
